# Generated by Django 4.2.4 on 2023-08-20 10:43

from django.db import migrations, models

import piepi.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=piepi.models.directory_path)),
                ("filename", models.CharField(max_length=255, unique=True)),
                ("sha256", models.CharField(max_length=64)),
                ("metadata", models.BinaryField(blank=True)),
                ("requires_python", models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
