# Generated by Django 4.2.4 on 2023-08-21 03:56

from django.db import migrations, models

import server.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(editable=False, max_length=255)),
                ("version", models.CharField(editable=False, max_length=64)),
                ("file", models.FileField(upload_to=server.models.directory_path)),
                (
                    "filename",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("sha256", models.CharField(editable=False, max_length=64)),
                ("metadata", models.BinaryField(blank=True)),
                (
                    "requires_python",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
            ],
        ),
    ]
